export function getStudentPhrases(): string {
  const phrases = [
    "F*ck That Assignment, Let's Chill!",
    "WiFi > GP@",
    "@ttendance? Never Heard of Her.",
    "Bro, Deadline Means Lifeline.",
    "Sutta + Chai = $urvival Mode",
    "Engineering Mein Sab @llowed Hai.",
    "Why Study When You Can Che@t?",
    "Lab Report = Copy + Paste + Hope",
    "One More Exam? Fu&K Me Already.",
    "Backlogs Are Just Side Chicks.",
    "Placement = Shaadi Proposal 2.0",
    "Hostel Life = Half Sleep, Full Stress",
    "Who Needs Sleep When You Have Backlogs?",
    "Bhai, CGPA Is Temporary. Memories Are Forever.",
    "F*ck Notes, Where's the Le@ked Paper?",
    "Khaana, Nind, Sutta — Pick Any Two.",
    "Exam Day = Friendship Day with Nerds",
    "Netflix > Net Present Value",
    "Syllabus Is Like My Ex — Too Long, Too Toxic.",
    "Backlog = Side Quest",
    "WiFi > GPA",
    "F*cK that b*cklog!",
    "Chai > Life",
    "Copy. Paste. Pray.",
    "@ttendance Scam",
    "Fest > Test",
    "Sutta + Chai = Degree",
    "Deadline = Lifeline",
    "Backbench > Front Row",
    "Notes? Send PDF",
    "Exam = Trauma Part 2",
    "No Sleep, Just Panic",
    "CGPA = Catastrophe",
    "Hostel = Chaos HQ",
    "Le@ked P@pers Here!",
    "Placement = Shaadi 2.0",
    "Lab = Copy Factory",
    "Mach’a Go Bunk!",
    "Backlog = Character Build",
    "Study? Nah, Bunk.",
    "Motivation: 404 Not Found",
    "Life = One Long Semester",
    "Leaked Paper > Lecture Notes",
    "Ctrl C + Ctrl V = GPA",
    "Open Book? Bro, My Friend's Book.",
    "Exam = Who Cheats Best Wins.",
    "Why study when WhatsApp exists?",
    "MCQs = My Chance to Guess.",
    "Leaked PDF: The Real Syllabus.",
    "Cheating? Nah, Collaborative Learning.",
    "Answer Key = Holy Grail.",
    "Handwriting? Just for Passing Chits.",
    "Exam Prep = Copying From Toppers.",
    "Backbench WiFi: Free Answers.",
    "Calculator? Nah, Full Cheat Sheet.",
    "GPA = Google Powered Assessment.",
    "Exams are basically group projects… with invigilators.",
  ];
  const randomIndex = Math.floor(Math.random() * phrases.length);

  return phrases[randomIndex];
}
